apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatroom-simulator
  labels:
    app: chatroom-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatroom-simulator
  template:
    metadata:
      labels:
        app: chatroom-simulator
    spec:
      containers:
      - name: chatroom-simulator
        image: python:3.12-alpine
        ports:
        - containerPort: 8080